//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeriesIDParser {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>8K</string>\r\n  <string>4320k</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ResMap_UltraHD8K {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ResMap_UltraHD8K"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>UHD</string>\r\n  <string>2160p</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ResMap_UltraHD {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ResMap_UltraHD"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>FullHD</string>\r\n  <string>1080p</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ResMap_FullHD {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ResMap_FullHD"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>HDTV</string>\r\n  <string>720p</string>\r\n  <string>HD</string>\r\n</ArrayOfSt" +
            "ring>")]
        public global::System.Collections.Specialized.StringCollection ResMap_HD {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ResMap_HD"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>DVDRIP</string>\r\n  <string>DVD</string>\r\n  <string>XVID</string>\r\n</ArrayO" +
            "fString>")]
        public global::System.Collections.Specialized.StringCollection ResMap_SD {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ResMap_SD"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>DUBBED</string>
  <string>SYNCED</string>
  <string>DL</string>
  <string>AVC</string>
  <string>German</string>
  <string>iTunes</string>
  <string>DTS</string>
  <string>BluRay</string>
  <string>x264</string>
  <string>x265</string>
  <string>h264</string>
  <string>AC3D</string>
  <string>AAC</string>
  <string>WebHD</string>
  <string>Netflix</string>
  <string>WebRIP</string>
  <string>DD20</string>
  <string>DD51</string>
  <string>8K</string>
  <string>UHD</string>
  <string>FULLHD</string>
  <string>1080P</string>
  <string>HDTV</string>
  <string>720P</string>
  <string>HD</string>
  <string>DVDRIP</string>
  <string>XVID</string>
  <string>DVD</string>
  <string>2160P</string>
  <string>MIRROR</string>
  <string>DOKU</string>
  <string>WEB</string>
  <string>BD9</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection RemoveToken {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["RemoveToken"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>3G2</string>
  <string>3GP</string>
  <string>AMV</string>
  <string>ASF</string>
  <string>AVI</string>
  <string>DRC</string>
  <string>F4A </string>
  <string>F4B</string>
  <string>F4P</string>
  <string>F4V</string>
  <string>FLV</string>
  <string>GIF</string>
  <string>GIFV</string>
  <string>M2V</string>
  <string>M4P </string>
  <string>M4V</string>
  <string>MKV</string>
  <string>MNG</string>
  <string>MOV</string>
  <string>MP2</string>
  <string>MP4</string>
  <string>MPE</string>
  <string>MPEG</string>
  <string>MPG</string>
  <string>MPV</string>
  <string>MXF</string>
  <string>NSV</string>
  <string>OGG</string>
  <string>OGV</string>
  <string>QT</string>
  <string>RM</string>
  <string>RMVB</string>
  <string>ROQ</string>
  <string>SVI</string>
  <string>VOB</string>
  <string>WEBM</string>
  <string>WMV</string>
  <string>YUV</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection FileExtensions {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["FileExtensions"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ReplaceSpaces {
            get {
                return ((bool)(this["ReplaceSpaces"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ReplaceDotHyphenDot {
            get {
                return ((bool)(this["ReplaceDotHyphenDot"]));
            }
        }
    }
}
