//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeriesIDParser {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>8K</string>\r\n  <string>4320P</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ResMap_UltraHD8K {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ResMap_UltraHD8K"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>UHD</string>\r\n  <string>2160P</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ResMap_UltraHD {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ResMap_UltraHD"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>FULLHD</string>\r\n  <string>1080P</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ResMap_FullHD {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ResMap_FullHD"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>HDTV</string>\r\n  <string>720P</string>\r\n  <string>HD</string>\r\n</ArrayOfSt" +
            "ring>")]
        public global::System.Collections.Specialized.StringCollection ResMap_HD {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ResMap_HD"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>DVDRIP</string>\r\n  <string>DVD</string>\r\n  <string>XVID</string>\r\n</ArrayO" +
            "fString>")]
        public global::System.Collections.Specialized.StringCollection ResMap_SD {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ResMap_SD"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>DUBBED</string>
  <string>SYNCED</string>
  <string>DL</string>
  <string>AVC</string>
  <string>GERMAN</string>
  <string>ITUNES</string>
  <string>DTS</string>
  <string>BLURAY</string>
  <string>X264</string>
  <string>H264</string>
  <string>AC3D</string>
  <string>AAC</string>
  <string>WEBHD</string>
  <string>NETFLIXUHD</string>
  <string>WEBRIP</string>
  <string>DD20</string>
  <string>DD51</string>
  <string>8K</string>
  <string>UHD</string>
  <string>FULLHD</string>
  <string>1080P</string>
  <string>HDTV</string>
  <string>720P</string>
  <string>HD</string>
  <string>DVDRIP</string>
  <string>XVID</string>
  <string>DVD</string>
  <string>2160P</string>
  <string>M4V</string>
  <string>MP4</string>
  <string>AVI</string>
  <string>WMV</string>
  <string>MPEG</string>
  <string>MPG</string>
  <string>FLV</string>
  <string>MKV</string>
  <string>MIRROR</string>
  <string>DOKU</string>
  <string>WEB</string>
  <string>BD9</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Remove_Token {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Remove_Token"]));
            }
        }
    }
}
